# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.0
  - nightly

os:
  - linux

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.add("BinDeps"); Pkg.build("RocksDB"); Pkg.test("RocksDB"; coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("RocksDB")); Pkg.add("RocksDB"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
